from fastapi import APIRouter, Depends, HTTPException, Header
from sqlalchemy.orm import Session
from app.db.session import get_db
from app.db import models
from pydantic import BaseModel
import secrets
import uuid
import datetime

router = APIRouter()

# --- Schemas ---

from typing import Optional

class AgentRegisterRequest(BaseModel):
    name: str # The "User Facing" ID
    description: Optional[str] = None

class RegisterResponse(BaseModel):
    agent_id: str # UUID
    api_key: str
    important: str = "SAVE THIS KEY NOW. IT WILL NOT BE SHOWN AGAIN."

class AgentProfile(BaseModel):
    agent_id: str
    name: str
    created_at: datetime.datetime
    stats: dict

import os

# --- Helpers ---

API_KEY_PREFIX = os.getenv("API_KEY_PREFIX", "ao_live_")

def generate_api_key():
    return API_KEY_PREFIX + secrets.token_hex(24)

def get_current_agent(authorization: str = Header(...), db: Session = Depends(get_db)) -> models.Agent:
    """
    Middleware to authenticate agent via API Key.
    Key: "Bearer ao_live_..."
    """
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid auth header format")
    
    api_key = authorization.replace("Bearer ", "")
    
    # Lookup key
    key_record = db.query(models.AgentKey).filter(
        models.AgentKey.api_key == api_key,
        models.AgentKey.revoked_at == None
    ).first()

    if not key_record:
        raise HTTPException(status_code=401, detail="Invalid or revoked API Key")

    # Fetch Agent
    agent = db.query(models.Agent).filter(models.Agent.id == key_record.agent_id).first()
    if not agent:
        raise HTTPException(status_code=401, detail="Agent not found")
        
    return agent

# --- Endpoints ---

@router.post("/register", response_model=RegisterResponse)
async def register_agent(req: AgentRegisterRequest, db: Session = Depends(get_db)):
    # 1. Check name uniqueness
    existing = db.query(models.Agent).filter(models.Agent.name == req.name).first()
    if existing:
        raise HTTPException(status_code=400, detail=f"Agent name '{req.name}' is already taken.")

    # 2. Create Agent
    new_agent = models.Agent(
        name=req.name,
        description=req.description,
        is_active=True
        # id will be auto-generated by DB or we can gen here if needed by logic
        # Since we just updated models to use server_default, we might need to flush to get ID if we don't set it.
        # But for safety, I'll set it here using uuid.uuid4 to ensure we have it for the Key record immediately.
    )
    new_agent.id = uuid.uuid4()
    
    db.add(new_agent)
    # Flush to ensure agent exists before ref
    db.flush()

    # 3. Generate Key
    api_key = generate_api_key()

    # 4. Create Key Record
    new_key = models.AgentKey(
        agent_id=new_agent.id,
        api_key=api_key,
        created_at=datetime.datetime.utcnow()
    )
    db.add(new_key)
    
    db.commit()

    return {
        "agent_id": str(new_agent.id),
        "api_key": api_key,
        "important": "SAVE THIS KEY NOW. IT WILL NOT BE SHOWN AGAIN."
    }

@router.get("/me", response_model=AgentProfile)
async def get_me(agent: models.Agent = Depends(get_current_agent)):
    return {
        "agent_id": str(agent.id),
        "name": agent.name,
        "created_at": agent.created_at,
        "stats": {} # Populate with real stats later if needed
    }

@router.get("/{name}", response_model=AgentProfile)
async def get_agent_profile(name: str, db: Session = Depends(get_db)):
    agent = db.query(models.Agent).filter(models.Agent.name == name).first()
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")
        
    return {
        "agent_id": str(agent.id),
        "name": agent.name,
        "created_at": agent.created_at,
        "stats": {
            "competitions": 0, # Placeholder
            "wins": 0,
            "avg_score": 0.0
        }
    }
